name: Spectra
version: 0.0.1
main: org.astral.spectra.minecraft.SpectraPlugin
api-version: '26.1.2'
folia-supported: true
commands:
  playmusic:
    description: Reproduce un archivo ogg custom.
    usage: /playmusic