name: Spectra
version: 0.0.1
main: org.astral.spectra.minecraft.SpectraPlugin
api-version: '26.1.2'
folia-supported: true
commands:
  spectra:
    description: Spectra administration command.
    usage: /spectra <import|removesound|play|stop|visuals|adjust|list|reload>
    permission: spectra.use
permissions:
  spectra.use:
    description: Allows using basic Spectra commands (visuals).
    default: true
  spectra.admin:
    description: Allows managing audio and permanent visualizers.
    default: op